APSSARA.G
Email id:apssaraganesh99@gmail.com



1)Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x




In [1]:
x = int(input("enter a number "))
import numpy as np
y = np.random.randint(0,x,(1,20))
y

enter a number 26


array([[ 7, 23, 16,  4, 12, 23,  8,  2, 17, 15, 17,  6, 21, 20, 12, 14,
         3, 19, 10,  3]])

2)Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10


In [8]:
arr = np.arange(300, 500, 10).reshape(4,5)
print (arr)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


3)Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values

In [12]:

import numpy as np
y = np.random.randint(-1000,1000,(20,20))
print(np.max(y))
print(np.min(y))
print(np.mean(y))

996
-1000
-49.65


4)In the following matrix, replace the last row with -1 Multiply the 2x2 matrix in the upper right corner by 2 X = [2 30 20 -2 -4] [3 4 40 -3 -2] [-3 4 -6 90 10] [25 45 34 22 12] [13 24 22 32 37]

In [4]:
X = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2], [-3, 4 ,-6, 90, 10] ,[25 ,45 ,34, 22 ,12], [13 ,24, 22 ,32, 37]])
X[-1: ] =  -1
print(X,'\n')

X[:2,3:] *= 2
print(X)


[[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]] 

[[ 2 30 20 -4 -8]
 [ 3  4 40 -6 -4]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]


5)In the following matrix, replace negative elements by 0 and replace odd elements with 25 X = [2 30 20 -2 -4] [3 4 40 -3 -2] [-3 4 -6 90 10] [25 45 34 22 12] [13 24 22 32 37]


In [6]:
import numpy as np
X = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2], [-3, 4 ,-6, 90, 10] ,[25 ,45 ,34, 22 ,12], [13 ,24, 22 ,32, 37]])
n = 0 
r = 0
print(np.where(X < n,r,X),'\n')

print(np.where( X % 2 == 1,25,X))


[[ 2 30 20  0  0]
 [ 3  4 40  0  0]
 [ 0  4  0 90 10]
 [25 45 34 22 12]
 [13 24 22 32 37]] 

[[ 2 30 20 -2 -4]
 [25  4 40 25 -2]
 [25  4 -6 90 10]
 [25 25 34 22 12]
 [25 24 22 32 25]]
